version: '3'
services:
  server:
    container_name: docker-node
    restart: always
    build: ./packages/server
    ports:
      - '5000:5000'
  client:
    container_name: docker-react
    restart: always
    build: ./packages/client
    ports:
      - 3000:3000
    links:
      - server
